spring.application.name=click-monitoring-service
# ======================
# SERVER
# ======================
server.port=8080

# ======================
# MYSQL CONFIG
# ======================
spring.datasource.url=jdbc:mysql://localhost:3306/educlick
spring.datasource.username=root
spring.datasource.password=Password@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# KAFKA
# ======================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=click-group
spring.kafka.consumer.auto-offset-reset=earliest

# ======================
# ACTUATOR
# ======================
management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true

# ======================
# CUSTOM
# ======================
app.kafka.topic=course-clicks

spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.kafka=DEBUG